version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - backend
    logging:
      driver: none

  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
      target: api_dev
    volumes:
      - ./api:/go/src/elastic_books/api
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    networks:
      - backend

volumes:
  data01:

networks:
  backend:
    driver: bridge