version: "3.8"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - backend

  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
      target: api_dev
    volumes:
      - ./api:/go/src/elastic_books/api
    ports:
      - "8080:8080"
    depends_on:
      - es01
    networks:
      - backend
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    environment:
      SERVER_NAME: kibana.elastic-books.local
      ELASTICSEARCH_URL: http://es01:9200
    depends_on:
      - es01
    ports:
      - "5601:5601"
    networks: 
      - backend

volumes:
  data01:
    driver: local

networks:
  backend: