version: "3.8"

services:
  elasticsearch:
    container_name: "elasticsearch"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    environment:
      - "transport.host=0.0.0.0"
      - "discovery.zen.minimum_master_nodes=1"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  api:
    build:
      context: ./
      dockerfile: Dockerfile
      target: api_dev
    volumes:
      - ./api:/go/src/elastic_books/api
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch

volumes:
  data01: